### ISSUE TITLE
論文公開に向けたリファクタリング

### ISSUE THREAD

**Issue by noshita** [MorphometricsGroup/Murata-2024#17]
## 背景
論文化の際にコードも公開したいので，リポジトリの構造も含め整備を進める．

### ToDo
- [x] #16
- [x] リポジトリの構造の整理 参考：[Cookiecutter Data Science](https://drivendata.github.io/cookiecutter-data-science/)
- [x] README.mdの作成
- [x] src内の構造を相談したい
- [x] 曲線ベース３次元再構築のパイプラインの整理
- [x] 主要な関数（e.g., ノートブックから呼び出される関数）へのdocstringの追加 @murata721 
- [x] ライセンスを決め，ファイルの設置 → [ISC](https://choosealicense.com/licenses/isc/)
- [x] 環境構築をどうするか決める → @murata721 conda， @noshita poetry 
- [x] #29 
- [x] 主要なデータのデータ構造を検討
    - [x] ファイル入出力しているものについては決定する
- [x] reprojection_gen, gen_support_dict/gen_supportとその関連関数の[broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html)対応 https://github.com/MorphometricsGroup/curve_sketch/issues/17#issuecomment-1210086959 #36 
    - [x] ファイル入出力の切り出し @noshita
      - [x] pair_and_key_gen
      - [x] coll_dict_gen
      - [x] pair_pt_gen 
    - [ ] 衝突判定の高速化 @noshita 
      - [ ] coll_t1_t2
      - [ ] PL_coll
    - [x] reprojection_gen @noshita 
        - [x] dot_P_frag
    - [x] gen_support_dict/gen_support  @murata721 
        - [ ] P_dict_check
            - [ ] cal_distance
            - [ ] distance_check
        - [ ] ac_list_integration
        - [ ] P_check_integration
- [x] **リアルデータ点群クラスタリング** @noshita
